### PR TITLE
Fix UTF-8 offset issues

### LINKED ISSUE #57: Cursor being put in wrong position

### PR DESCRIPTION
**Pull request by dbalatero**
Closes #57.

## Bugs

- [x] Down (j) won't go down
- [x] Big words (W) won't go to the end of the line

### CODE REVIEW

**Comment by dbalatero** [comment]
I'd really like to use this library: https://github.com/starwing/luautf8

I'm going to try vendoring it and see what happens.

**Comment by dbalatero** [comment]
This will make VimMode.spoon require Hammerspoon 0.9.79+, since we compiled the `.so` against Lua 5.4.

**Comment by yoricfr** [comment]
It works much better now! I have no issue with `w`, `b`, `e`, `f`
Otherwise, I encountered some minor issues:

Down (`j`) won't go down:

Big Words

It seems the function bellow return `true` when the cursor is on the first line.
```
 function Buffer:isOnLastLine()
   hs.printf("%s", "testing isOnLastLine()")
   hs.printf("%s", "self:getCurrentLineNumber(): " .. self:getCurrentLineNumber())
   hs.printf("%s", "self:getLineCount(): " .. self:getLineCount())
   return self:getCurrentLineNumber() == self:getLineCount()
 end
```
In my case, both `self:getCurrentLineNumber()` and `self:getLineCount()` are equal to `1`.

---

Big words (`W`) won't go to the end of the line:

Big Words

**Comment by dbalatero** [comment]
> Down (j) won't go down:

Yeah, I found some weirdness too. Also `k` sometimes won't go up. I had this in TextEdit (cursor denoted with `|`):

```
First line here.
Whatever.|
```

`k` would not go up a line, but if I tapped `j` it would move _left_ (!!) once. At this point, `j` and `k` started doing down/up again as normal. I'm curious if this is also broken in `master`.

> Big words (W) won't go to the end of the line:

Great, I added it to the PR description.

**Comment by yoricfr** [comment]
> `k` would not go up a line, but if I tapped `j` it would move _left_ (!!) once. At this point, `j` and `k` started doing down/up again as normal. I'm curious if this is also broken in `master`. It feels like it might not be a bug related to UTF-8 (especially since my input example above had no UTF-8 chars in it).

You're right, same bug in Master.

**Comment by yoricfr** [comment]
Backward search `F` has a shift:

```
First “line here.|
```
Pressing `F`+`n` results in:

```
First “line| here.
```

**Comment by dbalatero** [comment]
> You're right, same bug in Master.

Great - I will split that off to another issue / branch then.

> Backward search F and T has a shift:

Cool! I will fix and update the integration tests.

It's a little funny because the Vim cursor is the block-style cursor over the letter, and the OS has the line cursor after the character you're on. I consistently get tripped up by how they are "supposed" to work.

I tried to find a way to programmatically change the cursor type from the line caret to the block caret in OSX, but no such luck.

**Comment by yoricfr** [comment]
> It's a little funny because the Vim cursor is the block-style cursor over the letter, and the OS has the line cursor after the character you're on. I consistently get tripped up by how they are "supposed" to work.

Oh I came to the same conclusion.
At first I thought there was a bug using `t`, because the cursor seems so distant from the letter we're aiming at. While the block cursor is right behind, the caret cursor seems to be 1 char away from the correct position.
 
> I tried to find a way to programmatically change the cursor type from the line caret to the block caret in OSX, but no such luck.

That would be so cool!
It seems like the text cursor was not designed to be customized. Only specific applications allow this, like JetBrain IDE, or Terminal (caret, block, underscore).
A nice effect is to have a different cursor for insert mode and normal mode, with adding to the ~/.vimrc:

```
let &t_SI="\033[4 q" " start insert mode
let &t_EI="\033[1 q" " end insert mode
```

**Comment by dbalatero** [comment]
If I was insane, I would:

* use the accessibility API to get the bounding box of a text range in a field 
* draw a block cursor on top of the current position with some % opacity

but you'd have to maintain position as the cursor moves, and also it wouldn't work in half the fields anyways.

**Comment by yoricfr** [comment]
Muhahaha, love this.
Please be insane.
A crazy mind is a free mind, for it is boundless.
When there’s a will, there’s a way.
Coding get its magic when such bold creativity is put to the test.
Surprise is all we want.

I can’t see how it could be possible thought.
Imagine you can get the position of the cursor pixel-wise. Then you could draw a rectangle with some transparency (the killer detail!). But letter `i` being shorter than `m`, what about the box width? It would also depends on the text size and font.

The accessibility API is still obscure to me. I just learned about the `setAttributeValue()` function with passing the `AXSelectedTextRange` attribute, that magically change the cursor position and eventually the text selection.
I’m also new to Hammerspoon and this possibility to draw anything anywhere on screen is still stunning to me.

I bet there must be a library to handle the text cursor, like how much pixels for every letter within the current settings. Maybe in Swift / Objective-C? But anyway, the Accessibility API is all we have to get information and send orders whatever the active application.

**Comment by dbalatero** [comment]
https://stackoverflow.com/questions/36311582/caret-cursor-color-and-size
http://programming.jugglershu.net/wp/?p=765

These seem promising (obj-c though!)

**Comment by yoricfr** [comment]
Fascinating.
You just pointed to the right resource.
Now I want to install XCode to give it a try.

**Comment by yoricfr** [comment]
XVim2 works flawlessly on the latest Xcode 12.2 (beta)

It took me a while to:

1. Clean install Catalina 10.15.7 on my machine (it was so cluttered)
2. Download Xcode 12.2 beta (>11 Gb!)
3. `xip -x`  the downloaded file to actually install it
4. Clone and Make XVim2 (no issue)
5. Resign Xcode to use third-party plugins

The result is coool.

XVim-Xcode

I can't imagine if that cursor block could be invoked from the VimMode Spoon.

**Comment by dbalatero** [comment]
@yoricfr Are word motions fixed now? Also j/k up/down?

Make sure to quit + restart Hammerspoon to test.

**Comment by dbalatero** [comment]
Open new issues if you find anything!

**Pull request merged**
